language: C

os:
  - linux
  - osx
sudo: required
env:
  global:
    - DEPS_DIR="${HOME}/deps"
    # ANACONDA_TOKEN
    - secure: "a1Cozjl4QJ1/tWRY+7/d691coRyR98da98gDkVqyH/axdkieQFWHAnnsbKZto65lDOB9eilx8KT4ER/wNSdpf3bgPxe2mAaJcOkSazW0tfylxeAtoW8jf53bDqgHyUlBRoS8cJ5fbEmww6vHltPCtgD4u4x86UWSi1jTa2nJocfHv3Rc2YrbYOq5lLcnkz5rmDcnFFcmj9VlqpnEJjLTKFROBm8XvGF24O3aTht5whgkUfBiPViaZ9ppvbFX0hzqMSb0JXlyp2ixQGMSEsW1vCdZ++cwxxxdvgliKNfoKoUuqT+n5mgVyNppnRQJxn1cQxAAIOsdZDtc1/3ZB590Y9Yu6il+ELGncvN2z/L+sY7HhQ3NoVuMXI5+mDxYZeGfAIHEmnWo93WACPdxQ7aokQZcmTGezqPMONu7qvB9kL8ZxoCGLsSC8sbExkThVa3fhUwoiVNiz7OTjhbiZMRYa8XNO0igjzxqM5sHfQ1QkTvPkILDICdQ+S0LC0ztXgRMAgKBHuBTnNGreAk2yAb/gNFuIWQCPK2JlLPorr6Dc6dh6hgL2QbQnw7chuqZkEWCpvo84ZRELBo5qYbIIKWmqgd9MZcUjwCaMpKHmFAyL/3NV8GmtwZKhxG4DoFSZNBs4nDUcoTUKj0KxnwgVF774hzxem44RUQxZnFOjuwa7rw="
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"
install: bash ci/travis/install.sh
script:
 - bash ci/travis/script.sh

deploy:
  # Deploy on tags
  - provider: script
    script: "bash $TRAVIS_BUILD_DIR/ci/travis/deploy.sh"
    on:
      tags: true
    skip_cleanup: true

